include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-cc-switch
PKG_VERSION:=0.1.0
PKG_RELEASE:=1

PKG_LICENSE:=MIT
PKG_MAINTAINER:=kuno <noreply@github.com>

LUCI_TITLE:=LuCI support for Open CC Switch
LUCI_DEPENDS:=+cc-switch +rpcd-mod-ucode
LUCI_PKGARCH:=all

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
